# Generated by Django 3.1.1 on 2021-11-12 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_photo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='end_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='photo',
            name='type',
            field=models.CharField(choices=[('Interior', 'Interior'), ('Exterior', 'Exterior')], max_length=100),
        ),
    ]
