# Generated by Django 3.1.1 on 2021-11-30 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20211112_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='seller_nore',
            new_name='seller_note',
        ),
        migrations.AlterField(
            model_name='car',
            name='seller',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
