# Generated by Django 4.2 on 2023-06-05 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_car_end_at_alter_car_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_style',
            field=models.CharField(blank=True, choices=[('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('SUV/CUV', 'SUV/CUV'), ('Truck', 'Truck'), ('Van/Minivan', 'Van/Minivan'), ('Wagon', 'Wagon')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='drivetrain',
            field=models.CharField(blank=True, choices=[('Rear-wheel', 'Rear-wheel'), ('Front-wheel', 'Front-wheel'), ('All-wheel', 'All-wheel')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='end_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='equipment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='exterior_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='highlight',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='interior_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='known_flaw',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(blank=True, choices=[('BMW', 'BMW'), ('Toyota', 'Toyota'), ('Ford', 'Ford'), ('Honda', 'Honda')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='modification',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='ownership_history',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='recent_service_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='seller_note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='seller_type',
            field=models.CharField(blank=True, choices=[('Dealer', 'Dealer'), ('Customer', 'Customer')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='title_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('Automatic-Menual', 'Automatic with Menual')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission_speed',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
