# Generated by Django 4.2 on 2023-06-06 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_car_equipment_alter_car_highlight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.car'),
        ),
    ]
