# Generated by Django 4.2 on 2023-06-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_photo_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
