# Generated by Django 4.2 on 2023-06-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_car_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission_speed',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True),
        ),
    ]
