# Generated by Django 4.2 on 2023-06-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_car_transmission_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='on_auctiom',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
