# Generated by Django 4.2 on 2023-06-06 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_car_on_auctiom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='on_auctiom',
            new_name='on_auction',
        ),
    ]
