# Generated by Django 4.2 on 2023-06-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_car_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='bid',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
    ]
