# Generated by Django 4.2 on 2023-06-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_car_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(blank=True, choices=[('BMW', 'BMW'), ('Toyota', 'Toyota'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Jeep', 'Jeep'), ('Mercedes', 'Mercedes')], max_length=100, null=True),
        ),
    ]
